### ISSUE TITLE
Yaml: options per boxstyle

### ISSUE THREAD

**Issue by ute** [ute/custom-numbered-blocks#3]
(thinking loudly)
when (if) making an interface for other custom block styles, it would be logical to put options that affect the rendering/style, like `collapse`, as a subkey under the respective boxstyle key. This would however make the boxstyle key compulsory, and give endless cascades…
Default is foldbox

```yaml
groups:
   Theorem:
       boxstyle: {foldbox.simple, collapse=true}
```
       

???
